language: java

cache:
  directories:
    - ~/.m2


jdk:
  - oraclejdk15
  - oraclejdk11

matrix:
  allow_failures:
    - jdk: openjdk-ea

script:
  - mvn -V --no-transfer-progress
 
after_success:
  - mvn -V --no-transfer-progress clean test jacoco:report coveralls:report -Ptravis-jacoco javadoc:javadoc -Ddoclint=all
